services:
  - type: web
    name: webaxe-api
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npx playwright install --with-deps chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
